export const FLAG_MAP: { keys: string[]; flag: string }[] = [
  { keys: ["россия", "russia", "ru", "москв", "спб", "питер"], flag: "🇷🇺" },
  { keys: ["чехия", "czech", "cz", "прага", "prague"], flag: "🇨🇿" },
  { keys: ["германия", "germany", "de", "берлин", "франкфурт"], flag: "🇩🇪" },
  { keys: ["нидерланд", "netherlands", "nl", "амстердам"], flag: "🇳🇱" },
  { keys: ["франция", "france", "fr", "париж"], flag: "🇫🇷" },
  { keys: ["великобритания", "британия", "uk", "gb", "лондон"], flag: "🇬🇧" },
  { keys: ["сша", "usa", "us", "америк"], flag: "🇺🇸" },
  { keys: ["канада", "canada", "ca"], flag: "🇨🇦" },
  { keys: ["япония", "japan", "jp", "токио"], flag: "🇯🇵" },
  { keys: ["сингапур", "singapore", "sg"], flag: "🇸🇬" },
  { keys: ["турция", "turkey", "tr", "стамбул"], flag: "🇹🇷" },
  { keys: ["украина", "ukraine", "ua", "киев"], flag: "🇺🇦" },
  { keys: ["польша", "poland", "pl", "варшава"], flag: "🇵🇱" },
  { keys: ["финляндия", "finland", "fi", "хельсинки"], flag: "🇫🇮" },
  { keys: ["швеция", "sweden", "se"], flag: "🇸🇪" },
  { keys: ["норвегия", "norway", "no"], flag: "🇳🇴" },
  { keys: ["испания", "spain", "es"], flag: "🇪🇸" },
  { keys: ["италия", "italy", "it"], flag: "🇮🇹" },
  { keys: ["швейцария", "swiss", "ch"], flag: "🇨🇭" },
  { keys: ["австрия", "austria", "at"], flag: "🇦🇹" },
  { keys: ["казахстан", "kazakhstan", "kz"], flag: "🇰🇿" },
  { keys: ["китай", "china", "cn"], flag: "🇨🇳" },
  { keys: ["гонконг", "hong kong", "hk"], flag: "🇭🇰" },
  { keys: ["индия", "india", "in"], flag: "🇮🇳" },
  { keys: ["бразилия", "brazil", "br"], flag: "🇧🇷" },
  { keys: ["оаэ", "uae", "дубай", "dubai"], flag: "🇦🇪" },
  { keys: ["латвия", "latvia", "lv", "рига"], flag: "🇱🇻" },
  { keys: ["литва", "lithuania", "lt"], flag: "🇱🇹" },
  { keys: ["эстония", "estonia", "ee"], flag: "🇪🇪" },
];

export const FLAG_RE = /\p{Extended_Pictographic}/u;