project_id = "tyflywtpmeaqldzaoraj"

[functions.sub]
verify_jwt = false

[functions.hy2-auth]
verify_jwt = false

[functions.panel]
verify_jwt = false

[functions.admin-auth]
verify_jwt = false

[functions.ssh-cz-uuid]
verify_jwt = false