import { Client } from 'ssh2';
const conn = new Client();
conn.on('ready', () => {
  const commands = [
    'cat << "CADDY" > /etc/caddy/Caddyfile',
    '{',
    '  servers {',
    '    protocols h1 h2',
    '  }',
    '}',
    'web.panelsu.ru {',
    '  encode gzip',
    '  request_body {',
    '    max_size 200MB',
    '  }',
    '  reverse_proxy 127.0.0.1:8080',
    '}',
    'ru.panelsu.ru {',
    '  encode gzip',
    '  request_body {',
    '    max_size 200MB',
    '  }',
    '  reverse_proxy 127.0.0.1:2053',
    '}',
    'CADDY',
    'systemctl restart caddy',
    'systemctl status caddy --no-pager | head -n 10',
    'echo "=== HYSTERIA INSTALL ==="',
    'curl -L -o /usr/local/bin/hysteria https://github.com/apernet/hysteria/releases/latest/download/hysteria-linux-amd64',
    'chmod +x /usr/local/bin/hysteria',
    'mkdir -p /etc/hysteria',
    'cat << "YAML" > /etc/hysteria/config.yaml',
    'listen: :443',
    '',
    'tls:',
    '  cert: /root/.acme.sh/realityru.panelsu.ru_ecc/fullchain.cer',
    '  key: /root/.acme.sh/realityru.panelsu.ru_ecc/realityru.panelsu.ru.key',
    '',
    'auth:',
    '  type: password',
    '  password: TEST-KEY-REALITYRU-123',
    '',
    'masquerade:',
    '  type: proxy',
    '  proxy:',
    '    url: https://bing.com',
    '    rewriteHost: true',
    '',
    'outbounds:',
    '  - name: default',
    '    type: direct',
    'YAML',
    'cat << "SVC" > /etc/systemd/system/hysteria-server.service',
    '[Unit]',
    'Description=Hysteria Server',
    'After=network.target',
    '',
    '[Service]',
    'Type=simple',
    'ExecStart=/usr/local/bin/hysteria server -c /etc/hysteria/config.yaml',
    'WorkingDirectory=/etc/hysteria',
    'User=root',
    'Group=root',
    'Environment=GOGC=20',
    'Restart=always',
    'RestartSec=3s',
    'LimitNOFILE=1048576',
    '',
    '[Install]',
    'WantedBy=multi-user.target',
    'SVC',
    'systemctl daemon-reload',
    'systemctl enable hysteria-server.service',
    'systemctl restart hysteria-server.service',
    'systemctl status hysteria-server.service --no-pager | head -n 10',
    'ss -lunpt | grep -E "hysteria|443"'
  ];
  conn.exec(commands.join('\n'), (err, stream) => {
    stream.on('close', () => conn.end())
      .on('data', d => process.stdout.write(d.toString()))
      .stderr.on('data', d => process.stderr.write(d.toString()));
  });
}).connect({ host: '82.202.128.147', port: 22, username: 'root', password: 'K!E2QAGrxYFx' });